from __future__ import annotations

import re
from pathlib import Path

# Phase 1a: only known whitelist helpers → call gf_octave_planning.
# Real AST/subset comes later; keep 1:1 with octave_planning/common/*.m.

_CLAMP_M = re.compile(
    r"function\s+\w+\s*=\s*gf_clamp\s*\(\s*\w+\s*,\s*\w+\s*,\s*\w+\s*\)",
    re.M,
)

_HEADER = """\
// Generated by gf-octavecoder — DO NOT EDIT.
// Source: octave_planning (see PLAN.md). Rebuild via: python -m gf_octavecoder generate
"""


def _newest_mtime(paths: list[Path]) -> float:
    times = [p.stat().st_mtime for p in paths if p.is_file()]
    return max(times) if times else 0.0


def _oct_gen_stamp(oct_gen: Path) -> float:
    files = list(oct_gen.glob("*.cpp")) + list(oct_gen.glob("*.hpp"))
    return _newest_mtime(files)


def _emit_gf_clamp_hpp() -> str:
    return (
        _HEADER
        + """
#pragma once

#include "gf_octave_planning/clamp.hpp"

namespace oct_gen {

/** Corresponds to octave_planning/common/gf_clamp.m */
inline float gf_clamp(float x, float lo, float hi) {
  return gf_octave_planning::clamp(x, lo, hi);
}

}  // namespace oct_gen
"""
    )


def _emit_afc_lon_hpp() -> str:
    """Bridge: Octave name → gf_octave_planning (1:1 with m_lon_acc_aeb.m)."""
    return (
        _HEADER
        + """
#pragma once

#include "gf_octave_planning/lon_acc_aeb.hpp"

namespace oct_gen {

using gf_octave_planning::LonCtrl;
using gf_octave_planning::lon_exec;
using gf_octave_planning::lon_a_req;
using gf_octave_planning::plan_horizon;
using gf_octave_planning::plan_v_at_s;

/** Corresponds to octave_planning/afc/m_lon_acc_aeb.m */
inline LonCtrl m_lon_acc_aeb(float v, bool lead_valid, float d, float rel,
                             float lead_lat_m = 0.0f, float e_y = 0.0f, float c1 = 0.0f,
                             bool lane_valid = true) {
  return gf_octave_planning::m_lon_acc_aeb(v, lead_valid, d, rel, lead_lat_m, e_y, c1,
                                           lane_valid);
}

}  // namespace oct_gen
"""
    )


def _emit_afc_lat_lka_hpp() -> str:
    return (
        _HEADER
        + """
#pragma once

#include "gf_octave_planning/lat_lka.hpp"

namespace oct_gen {

using gf_octave_planning::lat_steer_from_lane;
using gf_octave_planning::lat_steer_from_ego;

/** Corresponds to octave_planning/afc/m_lat_lka.m */
inline float m_lat_lka(bool lane_valid, float e_y, float c1, float steer_angle_deg) {
  return gf_octave_planning::m_lat_lka(lane_valid, e_y, c1, steer_angle_deg);
}

}  // namespace oct_gen
"""
    )


def _emit_afc_lat_traj_hpp() -> str:
    return (
        _HEADER
        + """
#pragma once

#include "gf_octave_planning/lat_traj.hpp"

namespace oct_gen {

using gf_octave_planning::LatTraj;
using gf_octave_planning::kLatTrajPoints;
using gf_octave_planning::lat_poly_y;
using gf_octave_planning::lat_blend_alpha;
using gf_octave_planning::plan_fill_speed;

/** Corresponds to octave_planning/afc/m_lat_traj.m */
inline LatTraj m_lat_traj(float speed_mps, float D_see, float T_plan, bool lane_valid, float c0,
                          float c1, float c2, float c3, float x_end) {
  return gf_octave_planning::m_lat_traj(speed_mps, D_see, T_plan, lane_valid, c0, c1, c2, c3,
                                        x_end);
}

}  // namespace oct_gen
"""
    )


def generate_sku(*, repo_root: Path, sku: str, force: bool = False) -> int:
    m_common = repo_root / "octave_planning" / "common"
    m_sku = repo_root / "octave_planning" / sku
    oct_gen = (
        repo_root / "projects" / sku / "apps" / "planning" / "driving" / "oct_gen"
    )
    if not m_sku.is_dir():
        print(f"[gf-octavecoder] missing {m_sku}", flush=True)
        return 1

    sources = sorted(m_common.glob("*.m")) + sorted(m_sku.glob("*.m"))
    if not sources:
        print(f"[gf-octavecoder] no .m under {m_common} / {m_sku}", flush=True)
        return 1

    oct_gen.mkdir(parents=True, exist_ok=True)
    (oct_gen / ".gitkeep").touch(exist_ok=True)

    src_mtime = _newest_mtime(sources)
    out_mtime = _oct_gen_stamp(oct_gen)
    if not force and out_mtime >= src_mtime and (oct_gen / "gf_clamp.hpp").is_file():
        print(f"[gf-octavecoder] up-to-date ({sku}) → {oct_gen}", flush=True)
        return 0

    clamp_m = m_common / "gf_clamp.m"
    if clamp_m.is_file():
        text = clamp_m.read_text(encoding="utf-8")
        if not _CLAMP_M.search(text):
            print(f"[gf-octavecoder] refuse: {clamp_m} signature not whitelist", flush=True)
            return 1
        (oct_gen / "gf_clamp.hpp").write_text(_emit_gf_clamp_hpp(), encoding="utf-8")
        print(f"[gf-octavecoder] wrote {oct_gen / 'gf_clamp.hpp'}", flush=True)

    if sku == "afc":
        for name, emit in (
            ("m_lon_acc_aeb.m", _emit_afc_lon_hpp),
            ("m_lat_lka.m", _emit_afc_lat_lka_hpp),
            ("m_lat_traj.m", _emit_afc_lat_traj_hpp),
        ):
            src = m_sku / name
            if src.is_file():
                out = oct_gen / (src.stem + ".hpp")
                out.write_text(emit(), encoding="utf-8")
                print(f"[gf-octavecoder] wrote {out}", flush=True)

    print(f"[gf-octavecoder] OK sku={sku} → {oct_gen}", flush=True)
    return 0
