# P1 Track B/D: DDS + SOME/IP stubs (CycloneDDS default vendor; offline stub backend).
set(GF_SKU_APPLIED TRUE)
set(GF_SKU_VARIANT "bd_stub")

set(GF_WITH_ICEORYX OFF CACHE BOOL "" FORCE)
set(GF_WITH_SOMEIP ON CACHE BOOL "" FORCE)
set(GF_WITH_DDS ON CACHE BOOL "" FORCE)
set(GF_WITH_CROSS_DOMAIN_IPC OFF CACHE BOOL "" FORCE)

set(GF_RUNTIME_MODULES core com)
set(GF_APPS)
set(GF_DDS_BACKEND stub CACHE STRING "" FORCE)
