"""Spawn bricks: pick / place / ic / boundary / roles."""

from __future__ import annotations

from spawn.boundary import (
    ego_ok_for_continue,
    handoff_keep_ego,
    reset_wrecked_ego,
    sanitize_keep_ego,
)
from spawn.ic import (
    aeb_ego_seed,
    closing_along_heading,
    closing_along_pose,
    closing_const_fwd,
    closing_toward_lead,
    enable_constant_forward,
    freeze_motion,
    natural_continue,
    release_only,
    reset_vehicle_motion,
    seed_speed,
    set_forward_speed,
    set_natural_continue,
)
from spawn.pick import (
    prefer_center_lane,
    tf_on_lane,
    offset_transform,
    pick_curve_transform,
    pick_cut_in_transforms,
    pick_follow_transforms,
    pick_lead_ahead_of,
)
from spawn.place import (
    ego_lead,
    roll_npc,
    spawn_ego_lead,
    spawn_ego_only,
    spawn_named,
    spawn_walker_at,
)
from spawn.roles import (
    ROLE_EGO,
    ROLE_LEAD,
    clear_near,
    destroy_role,
    find_by_role,
    set_role,
    tick_world,
)

__all__ = [
    "ROLE_EGO",
    "ROLE_LEAD",
    "clear_near",
    "closing_along_heading",
    "closing_along_pose",
    "closing_const_fwd",
    "closing_toward_lead",
    "destroy_role",
    "ego_lead",
    "ego_ok_for_continue",
    "enable_constant_forward",
    "find_by_role",
    "freeze_motion",
    "handoff_keep_ego",
    "natural_continue",
    "offset_transform",
    "prefer_center_lane",
    "tf_on_lane",
    "pick_curve_transform",
    "pick_cut_in_transforms",
    "pick_follow_transforms",
    "pick_lead_ahead_of",
    "release_only",
    "reset_vehicle_motion",
    "reset_wrecked_ego",
    "sanitize_keep_ego",
    "seed_speed",
    "set_forward_speed",
    "aeb_ego_seed",
    "set_natural_continue",
    "set_role",
    "roll_npc",
    "spawn_ego_lead",
    "spawn_ego_only",
    "spawn_named",
    "spawn_walker_at",
    "tick_world",
]
