"""Emit CMake SKU fragment from req.yaml (P1-2)."""

from __future__ import annotations

from pathlib import Path
from typing import Any

# req.bindings entry → CMake GF_WITH_* cache var
_BINDING_FLAGS: dict[str, str] = {
    "iceoryx": "GF_WITH_ICEORYX",
    "someip": "GF_WITH_SOMEIP",
    "dds": "GF_WITH_DDS",
    "cross_domain_ipc": "GF_WITH_CROSS_DOMAIN_IPC",
}


def _cmake_bool(on: bool) -> str:
    return "ON" if on else "OFF"


def _cmake_list(values: list[str]) -> str:
    # space-separated; empty → empty set()
    return " ".join(values)


def emit_build_cmake(req: dict[str, Any], out_path: Path) -> None:
    """Write generated/gf_build.cmake from a parsed req dict."""
    variant = str(req.get("variant") or req.get("product") or "default")
    modules = [str(x) for x in (req.get("runtime_modules") or []) if str(x).strip()]
    apps = [str(x) for x in (req.get("apps") or []) if str(x).strip()]
    bindings = {str(x).strip() for x in (req.get("bindings") or []) if str(x).strip()}

    lines: list[str] = [
        "# Generated by gf_codegen.compose — do not edit by hand",
        f"# variant={variant}",
        "set(GF_SKU_APPLIED TRUE)",
        f'set(GF_SKU_VARIANT "{variant}")',
        "",
        "# --- bindings (req.bindings → GF_WITH_*) ---",
    ]
    for name, cmake_var in _BINDING_FLAGS.items():
        on = name in bindings
        lines.append(f'set({cmake_var} {_cmake_bool(on)} CACHE BOOL "" FORCE)')

    lines += [
        "",
        "# --- runtime modules / apps (consumed by cmake/GfModules.cmake) ---",
        f"set(GF_RUNTIME_MODULES {_cmake_list(modules)})",
        f"set(GF_APPS {_cmake_list(apps)})",
        "",
    ]

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
