"""Emit CMake SKU fragment from req.yaml (P1-2)."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from gf_codegen.compose.observability import (
    effective_apps,
    live_tap_config,
    normalize_profile,
    record_config,
)

# req.bindings entry → CMake GF_WITH_* cache var
_BINDING_FLAGS: dict[str, str] = {
    "iceoryx": "GF_WITH_ICEORYX",
    "someip": "GF_WITH_SOMEIP",
    "dds": "GF_WITH_DDS",
    "cross_domain_ipc": "GF_WITH_CROSS_DOMAIN_IPC",
}


def _cmake_bool(on: bool) -> str:
    return "ON" if on else "OFF"


def _cmake_list(values: list[str]) -> str:
    return " ".join(values)


def emit_observability_json(req: dict[str, Any], out_path: Path) -> None:
    """Host/runtime allowlists for tap + measure record."""
    live_en, live_svcs = live_tap_config(req)
    mode, rec_svcs = record_config(req)
    payload = {
        "profile": normalize_profile(req),
        "live_tap": {"enabled": live_en, "services": live_svcs},
        "record": {"mode": mode, "services": rec_svcs},
    }
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def emit_build_cmake(req: dict[str, Any], out_path: Path) -> None:
    """Write generated/gf_build.cmake from a parsed req dict."""
    variant = str(req.get("variant") or req.get("product") or "default")
    modules = [str(x) for x in (req.get("runtime_modules") or []) if str(x).strip()]
    apps = effective_apps(req)
    bindings = {str(x).strip() for x in (req.get("bindings") or []) if str(x).strip()}
    profile = normalize_profile(req)
    live_en, live_svcs = live_tap_config(req)

    lines: list[str] = [
        "# Generated by gf_codegen.compose — do not edit by hand",
        f"# variant={variant} profile={profile}",
        "set(GF_SKU_APPLIED TRUE)",
        f'set(GF_SKU_VARIANT "{variant}")',
        f'set(GF_SKU_PROFILE "{profile}")',
        f"set(GF_OBS_LIVE_TAP {_cmake_bool(live_en)})",
        "",
        "# --- bindings (req.bindings → GF_WITH_*) ---",
    ]
    for name, cmake_var in _BINDING_FLAGS.items():
        on = name in bindings
        lines.append(f'set({cmake_var} {_cmake_bool(on)} CACHE BOOL "" FORCE)')

    lines += [
        "",
        "# --- runtime modules / apps (consumed by cmake/GfModules.cmake) ---",
        f"set(GF_RUNTIME_MODULES {_cmake_list(modules)})",
        f"set(GF_APPS {_cmake_list(apps)})",
        "",
        f"# live_tap services: {', '.join(live_svcs) if live_svcs else '(none)'}",
        "",
    ]

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
