"""Emit OMG IDL from SOR types[] for CycloneDDS idlc (P1 Track D)."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

_SOR_TO_IDL: dict[str, str] = {
    "uint8": "uint8",
    "uint16": "uint16",
    "uint32": "uint32",
    "uint64": "uint64",
    "int8": "int8",
    "int16": "int16",
    "int32": "int32",
    "int64": "int64",
    "float32": "float",
    "float64": "double",
    "bool": "boolean",
    "string": "string",
    "bytes": "sequence<uint8>",
}


def _idl_type(sor_type: str) -> str:
    t = (sor_type or "").strip()
    if t.startswith("types."):
        return t.split(".")[-1]
    return _SOR_TO_IDL.get(t, t)


def _struct_name(type_id: str) -> str:
    tid = type_id.strip()
    if tid.startswith("types."):
        return tid[len("types.") :]
    return tid.replace(".", "_")


def emit_idl_from_sor(sor: dict[str, Any], *, module: str = "gf_types") -> str:
    """Return a single .idl file body for all struct types in SOR."""
    lines: list[str] = [
        "// Generated by gf-codegen emit-idl — do not edit by hand",
        f"module {module} {{",
        "",
    ]
    types = [t for t in (sor.get("types") or []) if isinstance(t, dict)]
    for t in types:
        if t.get("kind") not in (None, "struct"):
            continue
        name = _struct_name(str(t.get("id") or ""))
        if not name:
            continue
        lines.append(f"  struct {name} {{")
        fields = t.get("fields") or []
        if not fields:
            lines.append("    uint8 _placeholder;")
        for f in fields:
            if not isinstance(f, dict):
                continue
            fname = str(f.get("name") or "").strip()
            if not fname:
                continue
            ftype = _idl_type(str(f.get("type") or "uint8"))
            arr = f.get("array_size")
            if arr is not None:
                lines.append(f"    {ftype} {fname}[{int(arr)}];")
            else:
                lines.append(f"    {ftype} {fname};")
        lines.append("  };")
        lines.append("")
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def write_idl(sor_path: Path, out_dir: Path, *, module: str = "gf_types") -> Path:
    data = json.loads(sor_path.read_text(encoding="utf-8"))
    text = emit_idl_from_sor(data, module=module)
    out_dir.mkdir(parents=True, exist_ok=True)
    out = out_dir / "gf_types.idl"
    out.write_text(text, encoding="utf-8")
    return out
