"""Emit compile-frozen collector / bounds / ucm / diag DID tables from gf_ara_cfg_manifest.

Authoring YAML stays in gf-config; product runtime reads these headers only.
Smoke may still point GF_ARA_CFG_DIR at authoring platform for YAML fallback
when headers are not compiled in (middleware-only builds).
"""

from __future__ import annotations

from pathlib import Path
from typing import Any


def _c_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _as_int(v: Any, default: int) -> int:
    if v is None:
        return default
    try:
        return int(str(v), 0)
    except (TypeError, ValueError):
        return default


def _as_bool(v: Any, default: bool = False) -> bool:
    if v is None:
        return default
    if isinstance(v, bool):
        return v
    s = str(v).strip().lower()
    if s in ("1", "true", "yes", "on"):
        return True
    if s in ("0", "false", "no", "off"):
        return False
    return default


def emit_collector_config_hpp(manifest: dict[str, Any] | None, out_path: Path) -> None:
    body = (manifest or {}).get("collector") if isinstance(manifest, dict) else None
    if not isinstance(body, dict):
        body = {}
    forward = str(body.get("forward") or "local_store").strip() or "local_store"
    sources = [str(s).strip() for s in (body.get("sources") or []) if str(s).strip()]
    local = body.get("local") if isinstance(body.get("local"), dict) else {}
    local_enabled = _as_bool(local.get("enabled"), True)
    max_entries = _as_int(local.get("max_entries"), 256)
    debounce_max_keys = _as_int(local.get("debounce_max_keys"), 64)
    store_max_bytes = _as_int(local.get("store_max_bytes"), 1048576)
    dtc_rows = [e for e in (body.get("dtc_map") or []) if isinstance(e, dict)]
    freeze = [_as_int(x, 0) for x in (body.get("freeze_dids") or [])]
    freeze = [x for x in freeze if x]

    lines = [
        "// Generated by gf_codegen.compose — do not edit by hand",
        "#pragma once",
        "",
        "#include <cstdint>",
        "#include <cstddef>",
        "",
        "namespace gf_gen::collector {",
        "",
        f"inline constexpr const char* kForward = {_c_str(forward)};",
        f"inline constexpr bool kLocalEnabled = {'true' if local_enabled else 'false'};",
        f"inline constexpr std::uint32_t kMaxEntries = {max_entries}u;",
        f"inline constexpr std::uint32_t kDebounceMaxKeys = {debounce_max_keys}u;",
        f"inline constexpr std::uint32_t kStoreMaxBytes = {store_max_bytes}u;",
        "",
        "inline constexpr const char* kSources[] = {",
    ]
    for s in sources:
        lines.append(f"  {_c_str(s)},")
    lines += [
        "};",
        f"inline constexpr std::size_t kSourceCount = "
        f"sizeof(kSources) / sizeof(kSources[0]);",
        "",
        "struct DtcMapRow {",
        "  const char* event;",
        "  std::uint32_t dtc;",
        "  std::uint16_t debounce_count;",
        "  std::int16_t fdc_threshold;",
        "  std::uint16_t aging_cycles;",
        "};",
        "",
        "inline constexpr DtcMapRow kDtcMap[] = {",
    ]
    for e in dtc_rows:
        event = str(e.get("event") or "").strip()
        if not event:
            continue
        dtc = _as_int(e.get("dtc"), 0)
        if dtc == 0:
            continue
        deb = _as_int(e.get("debounce_count"), 1)
        fdc = _as_int(e.get("fdc_threshold"), 1)
        aging = _as_int(e.get("aging_cycles"), 40)
        lines.append(
            f"  {{{_c_str(event)}, {dtc:#07x}u, {deb}u, "
            f"static_cast<std::int16_t>({fdc}), {aging}u}},"
        )
    lines += [
        "};",
        f"inline constexpr std::size_t kDtcMapCount = "
        f"sizeof(kDtcMap) / sizeof(kDtcMap[0]);",
        "",
        "inline constexpr std::uint16_t kFreezeDids[] = {",
    ]
    for did in freeze:
        lines.append(f"  {did:#06x}u,")
    lines += [
        "};",
        f"inline constexpr std::size_t kFreezeDidCount = "
        f"sizeof(kFreezeDids) / sizeof(kFreezeDids[0]);",
        "",
        "}  // namespace gf_gen::collector",
        "",
    ]
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")


def emit_bounds_config_hpp(manifest: dict[str, Any] | None, out_path: Path) -> None:
    body = (manifest or {}).get("bounds") if isinstance(manifest, dict) else None
    if not isinstance(body, dict):
        body = {}
    com = body.get("com") if isinstance(body.get("com"), dict) else {}
    per = body.get("per") if isinstance(body.get("per"), dict) else {}
    dlt = body.get("dlt") if isinstance(body.get("dlt"), dict) else {}
    diag = body.get("diag") if isinstance(body.get("diag"), dict) else {}
    dids = diag.get("dids") if isinstance(diag.get("dids"), dict) else {}

    lines = [
        "// Generated by gf_codegen.compose — do not edit by hand",
        "#pragma once",
        "",
        "#include <cstdint>",
        "",
        "namespace gf_gen::bounds {",
        "",
        f"inline constexpr std::uint32_t kComQueueDepth = {_as_int(com.get('queue_depth'), 16)}u;",
        f"inline constexpr std::uint32_t kComMaxTopicKeys = {_as_int(com.get('max_topic_keys'), 64)}u;",
        f"inline constexpr std::uint32_t kPerMaxKeys = {_as_int(per.get('max_keys'), 1024)}u;",
        f"inline constexpr std::uint32_t kPerMaxValueBytes = "
        f"{_as_int(per.get('max_value_bytes'), 65536)}u;",
        f"inline constexpr std::uint32_t kDltMaxContexts = {_as_int(dlt.get('max_contexts'), 64)}u;",
        f"inline constexpr std::uint32_t kDiagRxMaxBytes = "
        f"{_as_int(diag.get('rx_max_bytes'), 65536)}u;",
        f"inline constexpr std::uint32_t kDidMaxEntries = {_as_int(dids.get('max_entries'), 256)}u;",
        f"inline constexpr std::uint32_t kDidMaxPayload = {_as_int(dids.get('max_payload'), 4096)}u;",
        "",
        "}  // namespace gf_gen::bounds",
        "",
    ]
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")


def emit_ucm_config_hpp(manifest: dict[str, Any] | None, out_path: Path) -> None:
    body = (manifest or {}).get("ucm") if isinstance(manifest, dict) else None
    if not isinstance(body, dict):
        body = {}
    enabled = _as_bool(body.get("enabled"), True)
    allow_rollback = _as_bool(body.get("allow_rollback"), True)
    allow_downgrade = _as_bool(body.get("allow_downgrade"), False)
    fg = str(body.get("function_group") or "MachineFG").strip() or "MachineFG"
    pkg = str(body.get("package_source") or "sil://artifact").strip() or "sil://artifact"

    lines = [
        "// Generated by gf_codegen.compose — do not edit by hand",
        "#pragma once",
        "",
        "namespace gf_gen::ucm {",
        "",
        f"inline constexpr bool kEnabled = {'true' if enabled else 'false'};",
        f"inline constexpr bool kAllowRollback = {'true' if allow_rollback else 'false'};",
        f"inline constexpr bool kAllowDowngrade = {'true' if allow_downgrade else 'false'};",
        f"inline constexpr const char* kFunctionGroup = {_c_str(fg)};",
        f"inline constexpr const char* kPackageSource = {_c_str(pkg)};",
        "",
        "}  // namespace gf_gen::ucm",
        "",
    ]
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")


def emit_diag_seed_hpp(manifest: dict[str, Any] | None, out_path: Path) -> None:
    body = (manifest or {}).get("diag") if isinstance(manifest, dict) else None
    if not isinstance(body, dict):
        body = {}
    dids = [d for d in (body.get("dids") or []) if isinstance(d, dict)]
    lines = [
        "// Generated by gf_codegen.compose — do not edit by hand",
        "#pragma once",
        "",
        "#include <cstdint>",
        "#include <cstddef>",
        "",
        "namespace gf_gen::diag {",
        "",
        "struct DidSeed {",
        "  std::uint16_t id;",
        "  const char* name;",
        "};",
        "",
        "inline constexpr DidSeed kDidSeeds[] = {",
    ]
    for d in dids:
        did = _as_int(d.get("id"), 0)
        name = str(d.get("name") or "").strip()
        if not did or not name:
            continue
        lines.append(f"  {{{did:#06x}u, {_c_str(name)}}},")
    lines += [
        "};",
        f"inline constexpr std::size_t kDidSeedCount = "
        f"sizeof(kDidSeeds) / sizeof(kDidSeeds[0]);",
        "",
        "}  // namespace gf_gen::diag",
        "",
    ]
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")


def emit_runtime_freeze(
    manifest: dict[str, Any] | None,
    gen_dir: Path,
) -> dict[str, str]:
    """Write collector/bounds/ucm/diag_seed headers. Always emit (defaults if empty)."""
    include = gen_dir / "include" / "gf_gen"
    collector = include / "collector_config.hpp"
    bounds = include / "bounds_config.hpp"
    ucm = include / "ucm_config.hpp"
    diag_seed = include / "diag_seed.hpp"
    emit_collector_config_hpp(manifest, collector)
    emit_bounds_config_hpp(manifest, bounds)
    emit_ucm_config_hpp(manifest, ucm)
    emit_diag_seed_hpp(manifest, diag_seed)
    return {
        "collector": str(collector),
        "bounds": str(bounds),
        "ucm": str(ucm),
        "diag_seed": str(diag_seed),
    }
