"""Emit compile-time frame_ingest config from req.yaml (behavior freeze).

Product path: frame_ingest_config.hpp only (apps + run_sil). No .env.
Tip ingress adaptation only — not FCM internals; not CARLA scenario scripts.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any


_VALID_SOURCES = frozenset({"none", "synth", "file", "carla_file"})
_VALID_BACKENDS = frozenset({"stub", "onnx"})
_VALID_PIXEL = frozenset({"nv12", "nv21", "yuv422", "yuv444", "rgb8"})
_VALID_EGO = frozenset({"gateway", "inject", "carla"})


def normalize_frame_ingest(req: dict[str, Any]) -> dict[str, Any]:
    """Return a fully filled frame_ingest dict (defaults = off / none)."""
    raw = req.get("frame_ingest")
    if not isinstance(raw, dict):
        raw = {}
    bridge = raw.get("bridge") if isinstance(raw.get("bridge"), dict) else {}
    paths = raw.get("paths") if isinstance(raw.get("paths"), dict) else {}

    source = str(raw.get("frame_source") or "none").strip() or "none"
    if source not in _VALID_SOURCES:
        source = "none"
    backend = str(raw.get("perception_backend") or "stub").strip() or "stub"
    if backend not in _VALID_BACKENDS:
        backend = "stub"

    pixel = str(raw.get("pixel_format") or "nv12").strip().lower() or "nv12"
    if pixel not in _VALID_PIXEL:
        pixel = "nv12"

    ego = str(raw.get("ego_source") or "gateway").strip().lower() or "gateway"
    if ego not in _VALID_EGO:
        ego = "gateway"

    frame_w = int(raw.get("frame_w") or bridge.get("frame_w") or 640)
    frame_h = int(raw.get("frame_h") or bridge.get("frame_h") or 480)
    if frame_w < 16:
        frame_w = 640
    if frame_h < 16:
        frame_h = 480

    frame_path = str(paths.get("frame") or "/tmp/gf_front.yuv")
    if frame_path.endswith(".rgb") and pixel != "rgb8":
        frame_path = frame_path[: -4] + ".yuv"

    return {
        "frame_source": source,
        "perception_backend": backend,
        "pixel_format": pixel,
        "ego_source": ego,
        "frame_w": frame_w,
        "frame_h": frame_h,
        "bridge": {
            "enabled": bool(bridge.get("enabled", False)),
        },
        "paths": {
            "frame": frame_path,
            "cmd": str(paths.get("cmd") or "/tmp/gf_carla_cmd.json"),
            "ego": str(paths.get("ego") or "/tmp/gf_carla_ego.json"),
            "truth": str(paths.get("truth") or "/tmp/gf_carla_truth.json"),
            "ctrl": str(paths.get("ctrl") or "/tmp/gf_planning_ctrl.json"),
        },
    }


def _c_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _cxx_bool(v: bool) -> str:
    return "true" if v else "false"


def emit_frame_ingest_hpp(cfg: dict[str, Any], out_path: Path) -> None:
    b = cfg["bridge"]
    p = cfg["paths"]
    lines = [
        "// Generated by gf_codegen.compose — do not edit by hand",
        "// Behavior freeze: change req.frame_ingest → compose → rebuild.",
        "// Tip ingress only. Scenarios live under repo carla_scenarios/.",
        "// run_sil / apps read this header; no frame_ingest.env.",
        "#pragma once",
        "",
        "#include <cstdint>",
        "",
        "namespace gf_gen::frame_ingest {",
        "",
        f"inline constexpr const char* kFrameSource = {_c_str(cfg['frame_source'])};",
        f"inline constexpr const char* kPerceptionBackend = {_c_str(cfg['perception_backend'])};",
        f"inline constexpr const char* kPixelFormat = {_c_str(cfg['pixel_format'])};",
        f"inline constexpr const char* kEgoSource = {_c_str(cfg['ego_source'])};",
        f"inline constexpr std::uint32_t kFrameW = {int(cfg['frame_w'])}u;",
        f"inline constexpr std::uint32_t kFrameH = {int(cfg['frame_h'])}u;",
        f"inline constexpr bool kBridgeEnabled = {_cxx_bool(b['enabled'])};",
        f"inline constexpr const char* kFramePath = {_c_str(p['frame'])};",
        f"inline constexpr const char* kCmdPath = {_c_str(p['cmd'])};",
        f"inline constexpr const char* kEgoPath = {_c_str(p['ego'])};",
        f"inline constexpr const char* kTruthPath = {_c_str(p['truth'])};",
        f"inline constexpr const char* kCtrlPath = {_c_str(p['ctrl'])};",
        "",
        "}  // namespace gf_gen::frame_ingest",
        "",
    ]
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")


def emit_frame_ingest(req: dict[str, Any], gen_dir: Path) -> dict[str, str]:
    """Emit hpp under project generated/. Returns output paths."""
    cfg = normalize_frame_ingest(req)
    hpp = gen_dir / "include" / "gf_gen" / "frame_ingest_config.hpp"
    emit_frame_ingest_hpp(cfg, hpp)
    legacy_env = gen_dir / "frame_ingest.env"
    if legacy_env.is_file():
        legacy_env.unlink()
    return {"hpp": str(hpp)}
