"""Emit iceoryx RouDi assets from bounds.yaml (BL-MEM-ROUDI)."""

from __future__ import annotations

from pathlib import Path
from typing import Any

# Defaults aligned with projects/.../platform/bounds.yaml
DEFAULT_MGMT: dict[str, int] = {
    "max_publishers": 32,
    "max_subscribers": 64,
    "max_subscribers_per_publisher": 8,
    "max_publisher_history": 4,
    "max_chunks_allocated_per_publisher": 2,
    "max_chunks_held_per_subscriber": 16,
    "max_interface_number": 2,
}

# bounds key → iceoryx CMake cache var
MGMT_TO_CMAKE: dict[str, str] = {
    "max_publishers": "IOX_MAX_PUBLISHERS",
    "max_subscribers": "IOX_MAX_SUBSCRIBERS",
    "max_subscribers_per_publisher": "IOX_MAX_SUBSCRIBERS_PER_PUBLISHER",
    "max_publisher_history": "IOX_MAX_PUBLISHER_HISTORY",
    "max_chunks_allocated_per_publisher": "IOX_MAX_CHUNKS_ALLOCATED_PER_PUBLISHER_SIMULTANEOUSLY",
    "max_chunks_held_per_subscriber": "IOX_MAX_CHUNKS_HELD_PER_SUBSCRIBER_SIMULTANEOUSLY",
    "max_interface_number": "IOX_MAX_INTERFACE_NUMBER",
}

DEFAULT_MEMPOOLS: list[dict[str, int]] = [
    {"size": 256, "count": 128},
    {"size": 1024, "count": 64},
    {"size": 4096, "count": 32},
]


def iceoryx_enabled(req: dict[str, Any] | None) -> bool:
    bindings = (req or {}).get("bindings") or []
    if not isinstance(bindings, list):
        return False
    return any(str(b).strip().lower() == "iceoryx" for b in bindings)


def extract_iox(bounds: dict[str, Any] | None) -> tuple[dict[str, int], list[dict[str, int]], int]:
    iox = (bounds or {}).get("iceoryx") if isinstance((bounds or {}).get("iceoryx"), dict) else {}
    mgmt_in = iox.get("mgmt") if isinstance(iox.get("mgmt"), dict) else {}
    mgmt = dict(DEFAULT_MGMT)
    for k in DEFAULT_MGMT:
        if k in mgmt_in and mgmt_in[k] is not None:
            try:
                mgmt[k] = int(mgmt_in[k])
            except (TypeError, ValueError):
                pass
    pools: list[dict[str, int]] = []
    raw = iox.get("mempools")
    if isinstance(raw, list) and raw:
        for p in raw:
            if not isinstance(p, dict):
                continue
            try:
                size = int(p.get("size") or 0)
                count = int(p.get("count") or 0)
            except (TypeError, ValueError):
                continue
            if size > 0 and count > 0:
                pools.append({"size": size, "count": count})
    if not pools:
        pools = [dict(x) for x in DEFAULT_MEMPOOLS]
    try:
        budget = int(iox.get("budget_shm_bytes") or 0)
    except (TypeError, ValueError):
        budget = 0
    return mgmt, pools, budget


def emit_iox_roudi_toml(path: Path, mempools: list[dict[str, int]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by gf-codegen compose from platform/bounds.yaml (BL-MEM-ROUDI).",
        "# Do not edit by hand — change bounds.iceoryx.mempools then re-compose.",
        "[general]",
        "version = 1",
        "",
        "[[segment]]",
        "",
    ]
    for p in mempools:
        lines.extend(
            [
                "[[segment.mempool]]",
                f"size = {int(p['size'])}",
                f"count = {int(p['count'])}",
                "",
            ]
        )
    path.write_text("\n".join(lines), encoding="utf-8")


def emit_iox_mgmt_cmake(path: Path, mgmt: dict[str, int]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by gf-codegen compose from platform/bounds.yaml (BL-MEM-ROUDI).",
        "# Maps to iceoryx CMake IOX_MAX_* (iceoryx_mgmt SHM size).",
        "# CHANGING THESE REQUIRES: cmake reconfigure + rebuild of iceoryx (and dependents).",
        "# Mempool / RouDi TOML changes only need restart of iox-roudi after compose.",
        "",
    ]
    for key, cmake_var in MGMT_TO_CMAKE.items():
        lines.append(f'set({cmake_var} {int(mgmt[key])} CACHE STRING "bounds.iceoryx.mgmt.{key}" FORCE)')
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def emit_iox_assets(
    out_dir: Path,
    platform: dict[str, Any],
    req: dict[str, Any] | None,
) -> dict[str, Any] | None:
    """Write iox_roudi.toml + iox_mgmt.cmake when req.bindings includes iceoryx.

    Returns meta dict for logging, or None if iceoryx not in SKU.
    """
    if not iceoryx_enabled(req):
        return None
    # Accept either {"bounds": {"iceoryx": ...}} or platform_manifest-style with bounds key
    bounds = platform.get("bounds") if isinstance(platform.get("bounds"), dict) else {}
    mgmt, pools, budget = extract_iox(bounds)
    emit_iox_roudi_toml(out_dir / "iox_roudi.toml", pools)
    emit_iox_mgmt_cmake(out_dir / "iox_mgmt.cmake", mgmt)
    return {
        "mgmt": mgmt,
        "mempools": pools,
        "budget_shm_bytes": budget,
        "toml": str(out_dir / "iox_roudi.toml"),
        "cmake": str(out_dir / "iox_mgmt.cmake"),
    }
