"""Emit compile-time frame_ingest config from req.yaml (behavior freeze).

Product path: frame_ingest_config.hpp only (apps + run_sil). No .env.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any


_VALID_SOURCES = frozenset({"none", "synth", "file", "carla_file"})
_VALID_BACKENDS = frozenset({"stub", "onnx"})


def normalize_frame_ingest(req: dict[str, Any]) -> dict[str, Any]:
    """Return a fully filled frame_ingest dict (defaults = off / none)."""
    raw = req.get("frame_ingest")
    if not isinstance(raw, dict):
        raw = {}
    bridge = raw.get("bridge") if isinstance(raw.get("bridge"), dict) else {}
    paths = raw.get("paths") if isinstance(raw.get("paths"), dict) else {}

    source = str(raw.get("frame_source") or "none").strip() or "none"
    if source not in _VALID_SOURCES:
        source = "none"
    backend = str(raw.get("perception_backend") or "stub").strip() or "stub"
    if backend not in _VALID_BACKENDS:
        backend = "stub"

    return {
        "frame_source": source,
        "perception_backend": backend,
        "bridge": {
            "enabled": bool(bridge.get("enabled", False)),
            "dry_run": bool(bridge.get("dry_run", True)),
            "demo_lane_change": bool(bridge.get("demo_lane_change", False)),
            "demo_lane_change_sec": int(bridge.get("demo_lane_change_sec") or 8),
        },
        "paths": {
            "frame": str(paths.get("frame") or "/tmp/gf_front.rgb"),
            "cmd": str(paths.get("cmd") or "/tmp/gf_carla_cmd.json"),
        },
    }


def _c_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _cxx_bool(v: bool) -> str:
    return "true" if v else "false"


def emit_frame_ingest_hpp(cfg: dict[str, Any], out_path: Path) -> None:
    b = cfg["bridge"]
    p = cfg["paths"]
    lines = [
        "// Generated by gf_codegen.compose — do not edit by hand",
        "// Behavior freeze: change req.frame_ingest → compose → rebuild.",
        "// run_sil / apps read this header; no frame_ingest.env.",
        "#pragma once",
        "",
        "#include <cstdint>",
        "",
        "namespace gf_gen::frame_ingest {",
        "",
        f"inline constexpr const char* kFrameSource = {_c_str(cfg['frame_source'])};",
        f"inline constexpr const char* kPerceptionBackend = {_c_str(cfg['perception_backend'])};",
        f"inline constexpr bool kBridgeEnabled = {_cxx_bool(b['enabled'])};",
        f"inline constexpr bool kBridgeDryRun = {_cxx_bool(b['dry_run'])};",
        f"inline constexpr bool kDemoLaneChange = {_cxx_bool(b['demo_lane_change'])};",
        f"inline constexpr std::uint32_t kDemoLaneChangeSec = {int(b['demo_lane_change_sec'])}u;",
        f"inline constexpr const char* kFramePath = {_c_str(p['frame'])};",
        f"inline constexpr const char* kCmdPath = {_c_str(p['cmd'])};",
        "",
        "}  // namespace gf_gen::frame_ingest",
        "",
    ]
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")


def emit_frame_ingest(req: dict[str, Any], gen_dir: Path) -> dict[str, str]:
    """Emit hpp under project generated/. Returns output paths."""
    cfg = normalize_frame_ingest(req)
    hpp = gen_dir / "include" / "gf_gen" / "frame_ingest_config.hpp"
    emit_frame_ingest_hpp(cfg, hpp)
    # Drop legacy env if present (no longer a behavior source).
    legacy_env = gen_dir / "frame_ingest.env"
    if legacy_env.is_file():
        legacy_env.unlink()
    return {"hpp": str(hpp)}
