"""Emit generated/include/gf_gen/platform_tables.hpp from platform_manifest."""

from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml


def _c_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def emit_platform_tables(manifest: dict[str, Any] | None, out_dir: Path) -> Path | None:
    """Write C++ lookup tables for exec/phm. Returns path or None if nothing to emit.

    Prefer product-frozen generated/exec.yaml (same filter as deploy_config) when present.
    """
    if not manifest and not (out_dir / "exec.yaml").is_file():
        return None

    exec_body = manifest.get("exec") if isinstance(manifest, dict) and isinstance(
        manifest.get("exec"), dict
    ) else {}
    phm_body = manifest.get("phm") if isinstance(manifest, dict) and isinstance(
        manifest.get("phm"), dict
    ) else {}
    # Product freeze wins over authoring exec (dlt/RouDi filtered).
    gen_exec = out_dir / "exec.yaml"
    if gen_exec.is_file():
        with gen_exec.open(encoding="utf-8") as f:
            loaded = yaml.safe_load(f) or {}
        if isinstance(loaded, dict) and isinstance(loaded.get("processes"), list):
            exec_body = loaded
    processes = [p for p in (exec_body.get("processes") or []) if isinstance(p, dict)]
    entities = [e for e in (phm_body.get("entities") or []) if isinstance(e, dict)]
    if not processes and not entities:
        return None

    lines: list[str] = [
        "// Generated by gf_codegen.compose — do not edit by hand",
        "#pragma once",
        "",
        "#include <cstdint>",
        "#include <string_view>",
        "",
        "namespace gf_gen::platform {",
        "",
        "struct ExecProcess {",
        "  const char* name;",
        "  const char* function_group;",
        "  bool execution_client;",
        "};",
        "",
        "struct PhmEntity {",
        "  const char* id;",
        "  const char* process;",
        "  std::uint32_t alive_period_ms;",
        "  std::uint32_t alive_timeout_ms;",
        "  const char* on_failure;  // log | notify_sm | restart",
        "};",
        "",
        "inline constexpr ExecProcess kExecProcesses[] = {",
    ]
    for p in processes:
        name = str(p.get("name") or "").strip()
        if not name:
            continue
        fg = str(p.get("function_group") or "MachineFG")
        # Platform daemons never speak ExecutionClient
        if name.startswith("host."):
            ec = False
        else:
            ec = bool(p.get("execution_client", True))
        lines.append(
            f"  {{{_c_str(name)}, {_c_str(fg)}, {'true' if ec else 'false'}}},"
        )
    lines.append("};")
    lines.append("")
    lines.append("inline constexpr PhmEntity kPhmEntities[] = {")
    for e in entities:
        eid = str(e.get("id") or "").strip()
        proc = str(e.get("process") or "").strip()
        if not eid or not proc:
            continue
        period = int(e.get("alive_period_ms") or 100)
        timeout = e.get("alive_timeout_ms")
        deadline = e.get("deadline_ms")
        # Prefer explicit alive_timeout; else deadline; else 3x period
        if timeout is not None:
            to = int(timeout)
        elif deadline is not None:
            to = int(deadline)
        else:
            to = period * 3
        on_fail = str(e.get("on_failure") or "log").strip() or "log"
        if on_fail not in ("log", "notify_sm", "restart"):
            on_fail = "log"
        lines.append(
            f"  {{{_c_str(eid)}, {_c_str(proc)}, {period}u, {to}u, {_c_str(on_fail)}}},"
        )
    lines.append("};")
    lines.append("")
    lines.append("inline const ExecProcess* FindExec(std::string_view process) {")
    lines.append("  for (const auto& p : kExecProcesses) {")
    lines.append("    if (process == p.name) return &p;")
    lines.append("  }")
    lines.append("  return nullptr;")
    lines.append("}")
    lines.append("")
    lines.append("inline const PhmEntity* FindPhm(std::string_view process) {")
    lines.append("  for (const auto& e : kPhmEntities) {")
    lines.append("    if (process == e.process) return &e;")
    lines.append("  }")
    lines.append("  return nullptr;")
    lines.append("}")
    lines.append("")
    lines.append("}  // namespace gf_gen::platform")
    lines.append("")

    header = out_dir / "include" / "gf_gen" / "platform_tables.hpp"
    header.parent.mkdir(parents=True, exist_ok=True)
    header.write_text("\n".join(lines), encoding="utf-8")
    return header
