"""Emit generated/include/gf_gen/ara_cfg_tables.hpp from gf_ara_cfg_manifest."""

from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml

from gf_codegen.compose.fg_schema import (
    normalize_active_in,
    normalize_function_groups,
)


def _c_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def emit_ara_cfg_tables(manifest: dict[str, Any] | None, out_dir: Path) -> Path | None:
    """Write C++ lookup tables for exec/phm. Returns path or None if nothing to emit.

    Prefer product-frozen generated/exec.yaml (same filter as deploy_config) when present.
    """
    if not manifest and not (out_dir / "exec.yaml").is_file():
        return None

    exec_body = manifest.get("exec") if isinstance(manifest, dict) and isinstance(
        manifest.get("exec"), dict
    ) else {}
    phm_body = manifest.get("phm") if isinstance(manifest, dict) and isinstance(
        manifest.get("phm"), dict
    ) else {}
    gen_exec = out_dir / "exec.yaml"
    if gen_exec.is_file():
        with gen_exec.open(encoding="utf-8") as f:
            loaded = yaml.safe_load(f) or {}
        if isinstance(loaded, dict) and isinstance(loaded.get("processes"), list):
            exec_body = loaded
    processes = [p for p in (exec_body.get("processes") or []) if isinstance(p, dict)]
    entities = [e for e in (phm_body.get("entities") or []) if isinstance(e, dict)]
    fgs = normalize_function_groups(exec_body.get("function_groups"))
    if not processes and not entities:
        return None

    lines: list[str] = [
        "// Generated by gf_codegen.compose — do not edit by hand",
        "#pragma once",
        "",
        "#include <cstdint>",
        "#include <string_view>",
        "",
        "namespace gf_gen::ara_cfg {",
        "",
        "enum class FgKind : std::uint8_t { kMachine = 0, kMode = 1 };",
        "",
        "struct FunctionGroup {",
        "  const char* id;",
        "  FgKind kind;",
        "  const char* initial;",
        "};",
        "",
        "struct ExecProcess {",
        "  const char* name;",
        "  const char* function_group;",
        "  bool execution_client;",
        "  const char* const* active_in;",
        "  std::size_t n_active_in;",
        "};",
        "",
        "struct PhmEntity {",
        "  const char* id;",
        "  const char* process;",
        "  std::uint32_t alive_period_ms;",
        "  std::uint32_t alive_timeout_ms;",
        "  const char* on_failure;  // log | notify_sm | restart",
        "};",
        "",
        "inline constexpr FunctionGroup kFunctionGroups[] = {",
    ]
    for fg in fgs:
        kind = "FgKind::kMode" if fg.get("kind") == "mode" else "FgKind::kMachine"
        lines.append(
            f"  {{{_c_str(fg['id'])}, {kind}, {_c_str(str(fg.get('initial') or ''))}}},"
        )
    lines.append("};")
    lines.append("")

    for p in processes:
        name = str(p.get("name") or "").strip()
        if not name:
            continue
        active = normalize_active_in(p.get("active_in"))
        if not active and p.get("drive_park_state") is not None:
            active = normalize_active_in(p.get("drive_park_state"))
        if active:
            ident = "".join(ch if ch.isalnum() else "_" for ch in name)
            lines.append(f"inline constexpr const char* kActiveIn_{ident}[] = {{")
            lines.append("  " + ", ".join(_c_str(s) for s in active) + ",")
            lines.append("};")
            lines.append("")

    lines.append("inline constexpr ExecProcess kExecProcesses[] = {")
    for p in processes:
        name = str(p.get("name") or "").strip()
        if not name:
            continue
        fg = str(p.get("function_group") or "MachineFG")
        if name.startswith("host."):
            ec = False
        else:
            ec = bool(p.get("execution_client", True))
        active = normalize_active_in(p.get("active_in"))
        if not active and p.get("drive_park_state") is not None:
            active = normalize_active_in(p.get("drive_park_state"))
        if active:
            ident = "".join(ch if ch.isalnum() else "_" for ch in name)
            active_ptr = f"kActiveIn_{ident}"
            n_active = str(len(active))
        else:
            active_ptr = "nullptr"
            n_active = "0"
        lines.append(
            f"  {{{_c_str(name)}, {_c_str(fg)}, {'true' if ec else 'false'}, "
            f"{active_ptr}, {n_active}u}},"
        )
    lines.append("};")
    lines.append("")
    lines.append("inline constexpr PhmEntity kPhmEntities[] = {")
    for e in entities:
        eid = str(e.get("id") or "").strip()
        proc = str(e.get("process") or "").strip()
        if not eid or not proc:
            continue
        period = int(e.get("alive_period_ms") or 100)
        timeout = e.get("alive_timeout_ms")
        deadline = e.get("deadline_ms")
        if timeout is not None:
            to = int(timeout)
        elif deadline is not None:
            to = int(deadline)
        else:
            to = period * 3
        on_fail = str(e.get("on_failure") or "log").strip() or "log"
        if on_fail not in ("log", "notify_sm", "restart"):
            on_fail = "log"
        lines.append(
            f"  {{{_c_str(eid)}, {_c_str(proc)}, {period}u, {to}u, {_c_str(on_fail)}}},"
        )
    lines.append("};")
    lines.append("")
    lines.append("inline const FunctionGroup* FindFunctionGroup(std::string_view id) {")
    lines.append("  for (const auto& g : kFunctionGroups) {")
    lines.append("    if (id == g.id) return &g;")
    lines.append("  }")
    lines.append("  return nullptr;")
    lines.append("}")
    lines.append("")
    lines.append("inline const ExecProcess* FindExec(std::string_view process) {")
    lines.append("  for (const auto& p : kExecProcesses) {")
    lines.append("    if (process == p.name) return &p;")
    lines.append("  }")
    lines.append("  return nullptr;")
    lines.append("}")
    lines.append("")
    lines.append("inline const PhmEntity* FindPhm(std::string_view process) {")
    lines.append("  for (const auto& e : kPhmEntities) {")
    lines.append("    if (process == e.process) return &e;")
    lines.append("  }")
    lines.append("  return nullptr;")
    lines.append("}")
    lines.append("")
    lines.append("}  // namespace gf_gen::ara_cfg")
    lines.append("")

    header = out_dir / "include" / "gf_gen" / "ara_cfg_tables.hpp"
    header.parent.mkdir(parents=True, exist_ok=True)
    header.write_text("\n".join(lines), encoding="utf-8")
    legacy = out_dir / "include" / "gf_gen" / "platform_tables.hpp"
    if legacy.is_file():
        legacy.unlink()
    return header
