"""Emit gf_gen/log_config.hpp from platform log (behavior freeze)."""

from __future__ import annotations

from pathlib import Path
from typing import Any


_LEVELS = frozenset({"FATAL", "ERROR", "WARN", "INFO", "DEBUG", "VERBOSE"})


def _c_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _norm_level(raw: Any, default: str = "INFO") -> str:
    s = str(raw or default).strip().upper() or default
    if s == "WARNING":
        s = "WARN"
    if s not in _LEVELS:
        return default
    return s


def normalize_log_config(platform: dict[str, Any] | None) -> dict[str, Any]:
    log = (platform or {}).get("log") if isinstance(platform, dict) else None
    if not isinstance(log, dict):
        log = {}
    sinks_in = log.get("sinks") or ["console"]
    sinks: list[str] = []
    if isinstance(sinks_in, list):
        for s in sinks_in:
            t = str(s).strip().lower()
            if t and t not in sinks:
                sinks.append(t)
    if not sinks:
        sinks = ["console"]
    dlt = log.get("dlt") if isinstance(log.get("dlt"), dict) else {}
    contexts: list[dict[str, str]] = []
    for c in log.get("contexts") or []:
        if not isinstance(c, dict):
            continue
        cid = str(c.get("id") or "").strip()
        if not cid:
            continue
        contexts.append({"id": cid, "level": _norm_level(c.get("level"), "INFO")})
    try:
        file_max = int(log.get("file_max_bytes") or 1048576)
    except (TypeError, ValueError):
        file_max = 1048576
    try:
        dlt_ctx = int(dlt.get("max_contexts") or log.get("dlt_max_contexts") or 64)
    except (TypeError, ValueError):
        dlt_ctx = 64
    color = str(log.get("color") or "auto").strip().lower() or "auto"
    if color not in ("on", "off", "auto", "true", "false"):
        color = "auto"
    if color == "true":
        color = "on"
    if color == "false":
        color = "off"
    return {
        "default_level": _norm_level(log.get("default_level"), "INFO"),
        "color": color,
        "sinks": sinks,
        "file_path": str(log.get("file_path") or "giraffe_modules.log"),
        "file_max_bytes": file_max,
        "dlt_app_id": str(dlt.get("app_id") or log.get("dlt_app_id") or "GFAP"),
        "dlt_max_contexts": dlt_ctx,
        "contexts": contexts,
    }


def emit_log_config_hpp(cfg: dict[str, Any], out_path: Path) -> None:
    lines = [
        "// Generated by gf_codegen.compose — do not edit by hand",
        "// log_config: platform/log.yaml → compose → rebuild. Product path: no log.yaml.",
        "#pragma once",
        "",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        "namespace gf_gen::log {",
        "",
        f"inline constexpr const char* kDefaultLevel = {_c_str(cfg['default_level'])};",
        f"inline constexpr const char* kColor = {_c_str(cfg['color'])};",
        f"inline constexpr const char* kFilePath = {_c_str(cfg['file_path'])};",
        f"inline constexpr std::uint32_t kFileMaxBytes = {int(cfg['file_max_bytes'])}u;",
        f"inline constexpr const char* kDltAppId = {_c_str(cfg['dlt_app_id'])};",
        f"inline constexpr std::uint32_t kDltMaxContexts = {int(cfg['dlt_max_contexts'])}u;",
        "",
        "inline constexpr const char* kSinks[] = {",
    ]
    for s in cfg["sinks"]:
        lines.append(f"  {_c_str(s)},")
    lines.append("};")
    lines.append(
        "inline constexpr std::size_t kSinkCount = "
        "sizeof(kSinks) / sizeof(kSinks[0]);"
    )
    lines.append("")
    lines.append("struct ContextEntry {")
    lines.append("  const char* id;")
    lines.append("  const char* level;")
    lines.append("};")
    lines.append("")
    lines.append("inline constexpr ContextEntry kContexts[] = {")
    for c in cfg["contexts"]:
        lines.append(f"  {{{_c_str(c['id'])}, {_c_str(c['level'])}}},")
    lines.append("};")
    lines.append(
        "inline constexpr std::size_t kContextCount = "
        "sizeof(kContexts) / sizeof(kContexts[0]);"
    )
    lines.append("")
    lines.append("}  // namespace gf_gen::log")
    lines.append("")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")


def emit_log_config(platform: dict[str, Any] | None, gen_dir: Path) -> dict[str, str]:
    cfg = normalize_log_config(platform)
    hpp = gen_dir / "include" / "gf_gen" / "log_config.hpp"
    emit_log_config_hpp(cfg, hpp)
    return {"hpp": str(hpp)}
